"""Non-sensitive serialized fixtures for Phase 01 type tests."""

HASH = "a" * 64


def payloads():
    gate = {
        "name": "task_correctness",
        "severity": "hard",
        "comparator": ">=",
        "threshold": 0.9,
        "suite_ref": "suite-seal",
        "checker_ref": "checker-1",
        "channel": "raw",
        "observed": 0.95,
        "passed": True,
        "evidence": ["artifact:evidence-1"],
    }
    brief = {
        "id": "brief-1",
        "version": 1,
        "brief_hash": HASH,
        "parent_version": None,
        "operator_session_id": "session-1",
        "raw_mission": "Improve the documented task behavior.",
        "dossier": {"deliverable": "release_tuple", "success_case": "works"},
        "hard_gate_approvals": [{"gate": "task_correctness", "approved": True}],
        "research_notes": [{"summary": "bounded note", "ref": "paper:1"}],
        "recipe_considerations": [{"recipe_id": "effect-a", "decision": "considered"}],
        "objective_ref": None,
        "created_at": "2026-08-08T00:00:00Z",
    }
    recipe = {
        "id": "effect-a",
        "version": "0.1.0",
        "title": "Grounded responses",
        "status": "draft",
        "effects": [{"id": "grounding", "direction": "increase", "measure": "grounding_rate"}],
        "scope": {"model_families": ["test"], "domains": ["test"], "interfaces": ["chat"]},
        "requires": [],
        "conflicts": [],
        "mechanism": "Visible evidence constrains targets.",
        "ingredients": {"data": {}, "training": {}, "interface": {}, "evaluation": {}},
        "procedure": ["admit", "smoke", "measure"],
        "tradeoffs": ["may reduce unsupported fluency"],
        "failure_modes": ["insufficient coverage"],
        "evidence": [{"ref": "artifact:evidence-1", "kind": "scorecard"}],
        "tested_uses": [],
        "interactions": {"compatible": [], "conflicts": [], "ordering": []},
        "provenance": {"curator": "human-1", "created": "2026-08-08"},
        "instruction_hash": HASH,
        "notes_head": None,
    }
    stack = {
        "id": "stack-1",
        "recipes": [{"id": "effect-a", "version": "0.1.0", "instruction_hash": HASH}],
        "overrides": {"learning_rate": 0.0001},
        "allocation": {"grounded": 0.5},
        "conflict_decisions": [],
        "validation_plan": {"suites": ["suite-seal"], "hard_gates": ["task_correctness"]},
        "stack_hash": HASH,
    }
    return {
        "Gate": gate,
        "GateResult": {**gate, "observed": 0.91},
        "MissionBrief": brief,
        "Objective": {
            "id": "objective-1",
            "mission_brief": {"id": "brief-1", "version": 1, "brief_hash": HASH},
            "intent": "Improve the documented task behavior.",
            "deliverable": "release_tuple",
            "gates": [gate],
            "constraints": {"no_self_distill": True},
            "budget": {"wall_time": 1, "gpu_hours": 1, "judge_tokens": 100, "smoke": 1, "scale": 1},
            "baselines": {"base": {"tuple_hash": HASH}},
            "suites": {"dev": {"ref": "suite-dev", "hash": HASH}, "seal": {"ref": "suite-seal", "hash": HASH}},
            "dependence_keys": ["scenario_id"],
            "mixture": None,
            "policy": {"human_promote": True},
            "interface": {"prompt_policy": HASH, "tool_schema": HASH, "decode": HASH},
            "recipe_policy": {"allowed": ["effect-a"], "max_stack": 1},
            "supersedes": None,
        },
        "ReleaseTuple": {
            "base_model": {"ref": "base", "hash": HASH},
            "adapter": None,
            "tokenizer": {"revision": "rev-1", "hash": HASH},
            "chat_template": HASH,
            "prompt_policy": {"id": "prompt-1", "hash": HASH},
            "tool_schema": {"id": "tools-1", "hash": HASH},
            "decode": {"id": "decode-1", "hash": HASH, "config": {"temperature": 0.2}},
            "guards": {"id": "guards-1", "hash": HASH},
            "recipe_stack": {"id": "stack-1", "hash": HASH},
            "tuple_hash": HASH,
        },
        "Run": {
            "run_id": "run-1",
            "objective_id": "objective-1",
            "mission_brief": {"id": "brief-1", "version": 1, "brief_hash": HASH},
            "stage": "admit",
            "status": "completed",
            "parents": [{"run_id": "run-0", "relation": "parent"}],
            "spec": {"seed": 1},
            "code_hash": HASH,
            "env": {"python": "3.14"},
            "hardware": {"cpu": "test"},
            "inputs": [],
            "outputs": [],
            "guard_report": None,
            "metrics_path": "runs/run-1/metrics.jsonl",
            "recipe_stack": {"id": "stack-1", "hash": HASH},
        },
        "Artifact": {"path": "artifacts/aa/item", "sha256": HASH, "role": "report", "producer_run_id": "run-1", "created_at": "2026-08-08T00:00:00Z", "media_type": "application/json"},
        "Scorecard": {"suite_hash": HASH, "seeds": [1], "decode_hash": HASH, "subject_tuple_hash": HASH, "recipe_stack_hash": HASH, "dimensions": {"correctness": 0.9}, "raw": {"correctness": 0.9}, "guarded": {"correctness": 0.91}, "findings": [], "slices": {}, "resources": {"wall_time": 1}},
        "Decision": {"action": "hold", "objective_id": "objective-1", "mission_brief_ref": {"id": "brief-1", "version": 1, "brief_hash": HASH}, "subject": {"tuple_hash": HASH}, "recipe_stack_ref": {"id": "stack-1", "hash": HASH}, "gate_results": [gate], "intervention": None, "human_requests": [], "dossier_ref": "artifact:dossier-1", "created_at": "2026-08-08T00:00:00Z"},
        "Recipe": recipe,
        "RecipeStack": stack,
        "Defect": {"id": "defect-1", "taxonomy": "over_specialize", "evidence": ["artifact:evidence-1"], "first_run_id": "run-1", "last_run_id": "run-1", "interventions": [], "status": "open"},
        "Policy": {"capabilities": {"train.smoke": True, "serve.flip_default": False}},
        "BudgetLedger": {"wall_time": 1, "gpu_hours": 1, "judge_tokens": 100, "smoke_runs": 1, "scale_runs": 1},
        "TrainCard": {"objective_id": "objective-1", "run_id": "run-1", "mission_brief": {"id": "brief-1", "version": 1, "brief_hash": HASH}, "parent_tuple_hash": HASH, "admission_report_hash": HASH, "mixture_counts": {"train": 2}, "interface_hashes": {"tokenizer": HASH}, "effective_examples": 2, "optimizer_steps": 1, "token_counts": {"target": 10}, "repeated_example_exposure": {"scenario-1": 1}, "target_length": {"mean": 5}, "lr_schedule": {"lr": 0.0001}, "seed": 1, "peak_vram": 1, "wall_time": 1, "teacher_id": "base", "reference_id": None, "best_checkpoint_ref": None, "recipe_stack_hash": HASH, "recipe_adaptations": []},
        "MixtureSpec": {"dimensions": ["domain", "source_class"], "floors": {"domain:test": 1}, "caps": {"domain:test": 10}, "quotas": {"replay": 1, "ood": 1}},
        "TargetShape": {"dimensions": ["domain", "source_class"], "floors": {"domain:test": 1}, "caps": {"domain:test": 10}, "quotas": {"replay": 1, "ood": 1}},
        "AdmissionReport": {"input_artifacts": [HASH], "keep_count": 2, "reject_count": 1, "reject_reasons": {"schema": 1}, "overlap_matrix": {"train_eval": 0, "train_seal": 0, "eval_seal": 0}, "near_dupes": {"rate": 0}, "template_families": {"family-a": 2}, "mixture_deltas": {}, "teacher_id": "base", "transformation_policy_id": "policy-1", "seeds": [1], "suite_hash": HASH, "passed": True, "gate_results": [gate]},
        "HumanInboxItem": {"id": "inbox-1", "objective_id": "objective-1", "gate_name": "taste", "payload_ref": "artifact:payload-1", "response_schema": {"type": "boolean"}, "created_at": "2026-08-08T00:00:00Z", "age": 0, "status": "pending"},
    }
